### ISSUE TITLE
DPL-542 As PSD developer I want to agree with TOL the next stage of the sample ingestion development

### ISSUE THREAD

**Issue by emrojo** [sanger/tol-lab-share#17]
**Description**
As PSD developer I want to agree with TOL the next stage of the development to provide a consumer to ingest samples from TOL into Traction because I want to coordinate any required changes in both sides to perform the coding of the solution.

**Who the primary contacts are for this work**
Eduardo Martin

**Knowledge or Stake holders**
Sujit Dey
TOL

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by stevieing** [comment]
Closed as done.
