### ISSUE TITLE
DPL-667 Bioscan - Support multiple root sources of the RabbitMQ export to Traction message

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/tol-lab-share#30]
**User story**
As PSD we need to modify the ToL Traction Consumer so that it can navigate the response to the correct source. (Consumer currently supports messages only from TOL, but it will also need to support messages from Limber/SS).

**Who are the primary contacts for this story**
PSD
Eduardo MJ

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Import of SS/Limber tubes into Traction via the consumer
- [ ] Response (feedback) to be routed to the correct queue for SS/Limber consumption

**Dependencies**
This story is blocked by the following dependencies:
- None

**References**
This story has a non-blocking relationship with:
- x

**Additional context**

**Comment by harrietc52** [comment]
Deprioritised in [DPL-694](https://github.com/sanger/General-Backlog-Items/issues/280)
