### ISSUE TITLE
DPL-753 Consumer to receive new QC fields from message queue (S=L,C=M)

### ISSUE THREAD

**Issue by emrojo** [sanger/tol-lab-share#36]
**User story**
As TOL I want to receive new QC fields from the queue:

Qc columns
- Sheared Femto Fragment Size (bp)
- Post SPRI Concentration (ng/ul)
- Post SPRI Volume (ul)
- Final NanoDrop 260/280
- Final NanoDrop 260/230
- Final NanoDrop ng/ul
- Shearing & QC comments (if applicable)
- Date submitted
- Priority level (if High or Medium)
- Date data required by
- Reason for priority

**Who are the primary contacts for this story**
Eduardo Martin

**Who is the nominated tester for UAT**
Charlie (TOL)

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Update the schema in consumer
- [x] Process the new qc columns in consumer and send it to traction
- [x] Process the new qc message in Traction and send it to warehouse

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>
- [DPL-753-1](https://github.com/sanger/tol-lab-share/issues/37)
- [DPL-753-2](https://github.com/sanger/tol-lab-share/issues/39)
- [DPL-754](https://github.com/sanger/traction-service/pull/1065)

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

Definition of fields in: https://docs.google.com/spreadsheets/d/1OW78PEbC8BzqV5TtRV9zV_4OU3t7HhCeBWSJv0rGno0/edit#gid=0

**Comment by TWJW-SANGER** [comment]
James has confirmed that that the long read QC data* in the message can be stored and viewed from the MLWH.
Once this story is done we can review if we can help Long Read deprecate the Google Sheet they are using to store and track this information.
*By Long Read QC data I mean these fields:
- Sheared Femto Fragment Size (bp)
- Post SPRI Concentration (ng/ul)
- Post SPRI Volume (ul)
- Final NanoDrop 260/280
- Final NanoDrop 260/230
- Final NanoDrop ng/ul
- Shearing & QC comments (if applicable)


The other fields in this story:

- Date submitted
- Priority level (if High or Medium)
- Date data required by
- Reason for priority

These can also be stored in the MLWH but it's worth noting that these fields will be common for all samples being submitted to SeqOps, so likely be used in different views.

**Comment by emrojo** [comment]
Tasks

A) UPDATE THE SCHEMA
- [ ] Setup local dev environment (Follow steps in https://github.com/sanger/tol-lab-share/blob/develop/SETUP_DOCKER.md)
- [ ] Add new qc fields into the schema
- [ ] Publish new schema in Redpanda in local (https://github.com/sanger/tol-lab-share/blob/develop/schemas/README.md)
- [ ] Modify current demo in tol-lab-share to include the testing data fields (tol-lab-share/tools/demo/testing_data.py)
- [ ] Start traction service in local and configure consumer to talk with traction service in local
- [ ] Run demo to publish new message and check that the consumer processes the message correctly
B) PROCESS THE FIELDS IN CONSUMER
- [ ] In tol_lab_share project, add new message properties for each of the new qc fields and add them as properties for a sample with no validation apart from checking is a string (check how it is with CommonName) (in message_properties/sample.py)
- [ ] Add the new properties into the traction message that we will send (in message_properties/labware.py). We need also to add the attributes to traction message interface to add the new fields 
- [ ] Modify traction message (OutputTractionMessage) to include the new fields in the payload we send
C) PROCESS THE FIELDS IN TRACTION

**Comment by harrietc52** [comment]
- [ ] update schema to add new columns for qc_results table
- [ ] new route in resource, for endpoint to create multiple qc results
- [ ] new controller for route
- [ ] new resource for route
- [ ] new factory, possibly being passed all the qc results to create. this loops through, creating the qc result, and if successful, building the message
- [ ] in factory, get the relevant assay types, using the tol `used_by` to filter them
- [ ] in factory, validation required assay types are present
- [ ] in the resource, if creation of qc results successful, access messages from the factory
- [ ] add config to build MLWH message to pipelines.yml
- [ ] publish message using factory messages and config
- [ ] edit rake task to add new assay types (confirm keys with tol, and check required units)
- [ ] add new `used_by` to assay type model for `tol`
- [ ]

**Comment by Sangeetha-Bheeman** [comment]
Steps to deploy:

1. Publish the new schema to red panda:

`push.sh <REDPANDA_URL> <API_KEY>`

For UAT(Use the right API KEY from vault):

`./push.sh https://redpanda.uat.tol.psd.sanger.ac.uk API_KEY`


2. Deploy tol-lab-share:

UAT:

`ansible-playbook -vD deploy_tol_lab_share.yml -i environments/uat -e "github_branch=0.2.0-5574405014-develop"
`

The new schema is deployed to UAT and it can be fetched as below (Use the right API-KEY):

`curl -H "Content-Type: application/vnd.schemaregistry.v1+json" -H "X-API-KEY: API-KEY" "https://redpanda.uat.tol.psd.sanger.ac.uk/subjects/create-labware/versions/latest"`

`{
  "subject": "create-labware",
  "version": 30,
  "id": 18,
  "schema": "{\"namespace\":\"uk.ac.sanger.psd\",\"type\":\"record\",\"name\":\"CreateLabwareMessage\",\"doc\":\"A create message to process new labware.\",\"fields\":[{\"name\":\"messageUuid\",\"doc\":\"Unique message ID.\",\"type\":{\"name\":\"version4MessageUuid\",\"type\":\"fixed\",\"size\":36}},{\"name\":\"messageCreateDateUtc\",\"doc\":\"Date (UTC) that the message was created.\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"labware\",\"doc\":\"Labware to process.\",\"type\":{\"name\":\"Labware\",\"type\":\"record\",\"doc\":\"Labware data.\",\"fields\":[{\"name\":\"labwareType\",\"type\":\"string\"},{\"name\":\"barcode\",\"type\":\"string\",\"doc\":\"The barcode for this labware.\"},{\"name\":\"samples\",\"doc\":\"An array of data for samples on the labware.\",\"type\":{\"type\":\"array\",\"items\":{\"name\":\"Sample\",\"type\":\"record\",\"doc\":\"A labware sample\",\"fields\":[{\"name\":\"sampleUuid\",\"doc\":\"Unique sample ID in UUID format.\",\"type\":\"version4MessageUuid\"},{\"name\":\"studyUuid\",\"doc\":\"Unique study UUID where the sample belongs to\",\"type\":\"version4MessageUuid\"},{\"name\":\"sangerSampleId\",\"type\":\"string\",\"doc\":\"Unique id to identify the sample inside Sanger lims\"},{\"name\":\"location\",\"type\":\"string\",\"doc\":\"The location for the sample inside the labware, or null if location is not relevant in labware (Eg: tube).\"},{\"name\":\"supplierSampleName\",\"type\":\"string\",\"doc\":\"Name given by the supplier of the sample\"},{\"name\":\"volume\",\"type\":\"string\",\"doc\":\"Volume of the sample.\"},{\"name\":\"concentration\",\"type\":\"string\",\"doc\":\"Concentration of the sample.\"},{\"name\":\"publicName\",\"type\":\"string\",\"doc\":\"Public name of the sample.\"},{\"name\":\"taxonId\",\"type\":\"string\",\"doc\":\"Taxonomy Identifier.\"},{\"name\":\"commonName\",\"type\":\"string\",\"doc\":\"Common name for the sample\"},{\"name\":\"donorId\",\"type\":\"string\",\"doc\":\"Identifier for the donor of the sample\"},{\"name\":\"libraryType\",\"type\":\"string\",\"doc\":\"Type of library created for sequencing\"},{\"name\":\"countryOfOrigin\",\"type\":\"string\",\"doc\":\"Country of origin for the sample\"},{\"name\":\"sampleCollectionDateUtc\",\"doc\":\"Sample Collection of the sample in UTC format.\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"costCode\",\"type\":\"string\",\"doc\":\"Code for the project for billing purposes\"},{\"name\":\"genomeSize\",\"type\":\"string\",\"doc\":\"Size of genome\"},{\"name\":\"accessionNumber\",\"type\":\"string\",\"doc\":\"Accession number for publication in ENA/EBI\"},{\"name\":\"shearedFemtoFragmentSize\",\"type\":\"string\",\"doc\":\"Sheared Femto Fragment Size\"},{\"name\":\"postSPRIConcentration\",\"type\":\"string\",\"doc\":\"Post SPRI Concentration (ng/ul)\"},{\"name\":\"postSPRIVolume\",\"type\":\"string\",\"doc\":\"Post SPRI Volume (ul)\"},{\"name\":\"finalNanoDrop280\",\"type\":\"string\",\"doc\":\"Final NanoDrop 260/280\"},{\"name\":\"finalNanoDrop230\",\"type\":\"string\",\"doc\":\"Final NanoDrop 260/230\"},{\"name\":\"finalNanoDrop\",\"type\":\"string\",\"doc\":\"Final NanoDrop ng/ul\"},{\"name\":\"shearingAndQCComments\",\"type\":\"string\",\"doc\":\"Shearing & QC comments\"},{\"name\":\"dateSubmittedUTC\",\"doc\":\"Date submitted in UTC format.\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"priorityLevel\",\"type\":\"string\",\"doc\":\"Priority level (if High or Medium)\"},{\"name\":\"dateRequiredBy\",\"type\":\"string\",\"doc\":\"Date data required by\"},{\"name\":\"reasonForPriority\",\"type\":\"string\",\"doc\":\"Reason for priority\"}]}}}]}}]}"
}`

**Comment by Sangeetha-Bheeman** [comment]
Closing this, as all the tasks in this are being tracked as part of DPL- 753-1, DPL-753-2 and DPL-754.
