### ISSUE TITLE
DPL-1068 - As developers we need to investigate how to use the enterprise message queue to support volume tracking

### ISSUE THREAD

**Issue by stevieing** [sanger/tol-lab-share#57]
**Description**
As developers we need to investigate how to use the enterprise message queue to support volume tracking:
- is it better to use the message queue currently in traction or would it make sense to move to a better model which is more maintainable and scalable?
- should we create a createAliquot message avro schema?
- do ToL need to be able to pull messages off the queue or will they use the warehouse?

**Who the primary contacts are for this work**
Steve / Ben / Stuart?

**Knowledge or Stake holders**
ToL

**Additional context or information**
- If we decide to go ahead with the enterprise message queue there will be more stories. The output of this story should be a document listing the pros and cons of each solution along with a decision plus a process diagram of how messaging will work.
- We should consult with Long Read and maybe Scientific Operations management on how they would report.
- We should also consult with ToL about how they would use this 

- Volume checking process map: [https://lucid.app/lucidchart/3c12fbb3-5265-49b5-9f6a-97c9a69a59eb/edit?viewport_l[…]3271%2C0_0&invitationId=inv_4a6b1f8d-e886-4ffc-b784-40f2135c0679](https://lucid.app/lucidchart/3c12fbb3-5265-49b5-9f6a-97c9a69a59eb/edit?viewport_loc=116%2C-4472%2C6583%2C3271%2C0_0&invitationId=inv_4a6b1f8d-e886-4ffc-b784-40f2135c0679)
- Multiplexing ERD: https://lucid.app/lucidchart/56eec268-2911-44c4-ab4b-87393e811738/edit?view_items=Fm2l5AbOONXb&invitationId=inv_81ba033e-8594-44c3-a37f-fd0c07fb4803
- Multiplexing process map: https://lucid.app/lucidchart/343de76c-d3e5-4a26-92c4-7bc10d919fb8/edit?page=0_0&invitationId=inv_13a8dd3b-ef1b-4f4e-b160-0dbf45a6031f#

**Comment by stevieing** [comment]
Outline of stories:

- create a process diagram for the data flow (todo as part of this story)
- create a connection between traction and the enterprise message queue
- define an avro schema for aliquots
- create new exchanges on the enterprise system to receive those messages
- define a new message on ToL labshare to consume the messages
- setup a connection between ToL lab share and the multi lims warehouse
- user account for ToL labshare to connect to warehouse rabbit mq
- create a second message queue which is not consumed and will expire messages to provide a backlog of messages which could be republished

**Comment by dasunpubudumal** [comment]
The draft process diagram is [here in LucidChart](https://lucid.app/lucidchart/6c8d5b09-4e57-4aba-a7ff-8d2cad161b3d/edit?viewport_loc=-279%2C-115%2C3268%2C1556%2C0_0&invitationId=inv_9886517c-b0aa-4670-9e87-d820b8ddbba7). As of 13/05/2024, it's still work-in-progress.
