### ISSUE TITLE
Y24-039 Addition of sample "RETENTION INSTRUCTION" field in automated manifests (used by ToL)

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/tol-lab-share#85]
**User story**
As an SSR, I want sample destruction/retention instructions for all samples to be recorded when samples are receieved through the ToL automated manifest messages  to allow for correct audit tracking.

This data ensures samples are not destroyed by mistake and allows effective sample return to the sample custodians. This is an essential function that allows teams to follow the SeqOps sample retention & destruction policy.

**Who are the primary contacts for this story**
Nathalie S., Alice

**Who is the nominated tester for UAT**
Alice
- To confirm she can see retention instructions for plates/samples received by automated manifest - this could be done by the team if we know where she is looking

**Acceptance criteria**
To be considered successful the solution must allow:

- [ ]  All messages received on the current message schema version are treated as implicitly specifying "Return to customer after 2 years" for the retention field
- [ ]  We create a new version of the message schema that includes a new required parameter “retention_instruction” for each plate/tube submitted.
- [ ]  Documentation to describe the both message schema versions is updated and shared with stakehoders.
- [ ]  Our message consumers are updated to support both message schema versions.

This will allow ToL to continue to submit samples without changing their systems, until they need to vary the retention instruction.

References
This story has a non-blocking relationship with:
https://rt.sanger.ac.uk/Ticket/Display.html?id=799922

**Additional context**

**Comment by stevieing** [comment]
4 stories:
- update the schema
- update ToL lab share
- update traction service
- update unified warehouse

**Comment by dasunpubudumal** [comment]
Stories:

1. https://github.com/sanger/General-Backlog-Items/issues/412
2. https://github.com/sanger/tol-lab-share/issues/121
3. https://github.com/sanger/traction-service/issues/1349
4. https://github.com/sanger/unified_warehouse/issues/633
